### ISSUE TITLE
cant require swift class from framework via hyperloop

### ISSUE THREAD

**Issue by mandelmonkey** [hansemannn/titanium-swift-module-example#1]
I added an ios framework to my project which has the framework header MyFrameWork.h and the swift class file MyFrameWork.swift

however im not sure how to access functions from the MyFrameWork.swift, maybe because there are no headers for the swift file?

inside appcelerator project I am calling require("MyFrameWork/MyFrameWork")

**Comment by hansemannn** [comment]
Sorry, but this is totally unrelated to this project. It's about Swift-based native modules here.
