### ISSUE TITLE
Renaming project?

### ISSUE THREAD

**Issue by jasonsultana** [hansemannn/titanium-swift-module-example#3]
After upgrading the project to use Swift 5 and a couple of other small updates, I can get this to build and import into Appcelerator Titanium. But if I rename the module, Titanium fails complaining that it can't find the module for architecture x86_64. Is there a straight-forward way to rename this project from ti.test to something else?

I've seen https://platform.axway.com/?redirect=https%3A%2F%2Fdevblog.axway.com%2Fmobile-apps%2Fwrite-titanium-ios-native-modules-swift%2F, which suggests that the CLI now supports creating Swift modules, but I can't reproduce that behaviour - it always creates an Objective C module. Do you know if this behaviour has been rolled back?

**Comment by jasonsultana** [comment]
I'll answer my own question here. I was confused between the `appc` command line tool and the `ti` command line tool. I somehow had assumed that `appc` superseded `ti`, but it looks like only the `ti` tool got the latest updates?

https://docs.axway.com/bundle/Titanium_SDK_allOS_en/page/titanium_command-line_interface_reference.html

https://jira.appcelerator.org/browse/TIMOB-17887

Creating new swift projects works with `ti`, but not with `appc ti`. Sorry for all the noise, but hopefully my ramblings may help someone else who was confused by this.

**Comment by hansemannn** [comment]
Thanks @jasonsultana! Can you inform the Axway team about this please? I assume @sgtcoolguy would be like to know this.
